#
# Module manifest for module 'PrtgSensorKit'
#
# Generated by: ArchitektApx
#
# Generated on: 18.02.2026
#

@{

RootModule = 'PrtgSensorKit.psm1'

ModuleVersion = '0.0.0'

CompatiblePSEditions = 'Core', 'Desktop'

GUID = '1b9c2a92-c7fe-40f4-a537-2a14f2268150'

Author = 'ArchitektApx'

Copyright = 'Copyright 2026 ArchitektApx'

Description = 'PowerShell framework for building PRTG custom sensors less boilerplate, valid output every time.'

PowerShellVersion = '5.1.0'

RequiredModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Add-PrtgChannel',
    'Clear-PrtgOutput',
    'Clear-PrtgSensorState',
    'Get-PrtgMessage',
    'Get-PrtgSecret',
    'Get-PrtgSensorState',
    'Invoke-PrtgSensor',
    'Invoke-PrtgSensorDoctor',
    'New-PrtgChannel',
    'Restart-As64BitPowershell',
    'Restart-InPwsh',
    'Save-PrtgSecret',
    'Save-PrtgSensorState',
    'Set-PrtgMessage',
    'Set-PrtgOutput',
    'Use-PrtgCachedResult',
    'Write-PrtgError',
    'Write-PrtgLog',
    'Write-PrtgOutput'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

PrivateData = @{

    PSData = @{

        Tags = @('PRTG', 'Monitoring', 'Sensor', 'Custom-Sensor', 'PowerShell', 'Pwsh', 'Framework')

        LicenseUri = 'https://github.com/ArchitektApx/PrtgSensorKit/blob/master/LICENSE'

        ProjectUri = 'https://github.com/ArchitektApx/PrtgSensorKit'

        # Shown on the PowerShell Gallery page; the changelog is the single source of truth.
        ReleaseNotes = 'https://github.com/ArchitektApx/PrtgSensorKit/blob/master/CHANGELOG.md'

        # Prerelease tag placeholder; ModuleBuilder can only stamp a prerelease SemVer
        # into the built manifest when this key exists.
        Prerelease = ''

    }

 }

}

