#
# Module manifest for module 'PrtgSensorKit'
#
# Generated by: ArchitektApx
#
# Generated on: 18.02.2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PrtgSensorKit.psm1'

# Version number of this module.
ModuleVersion = '0.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '1b9c2a92-c7fe-40f4-a537-2a14f2268150'

# Author of this module
Author = 'ArchitektApx'

# Copyright statement for this module
Copyright = 'Copyright 2026 ArchitektApx'

# Description of the functionality provided by this module
Description = 'PowerShell framework for building PRTG custom sensors less boilerplate, valid output every time.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1.0'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('PRTG', 'Monitoring', 'Sensor', 'Custom-Sensor', 'PowerShell', 'Pwsh', 'Framework')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/ArchitektApx/PrtgSensorKit/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ArchitektApx/PrtgSensorKit'

        # Shown on the PowerShell Gallery page; the changelog is the single source of truth.
        ReleaseNotes = 'https://github.com/ArchitektApx/PrtgSensorKit/blob/master/CHANGELOG.md'

        # Prerelease tag placeholder; ModuleBuilder can only stamp a prerelease SemVer
        # into the built manifest when this key exists.
        Prerelease = ''

    }

 }

}

